#!/bin/bash

# apt -y install unzip

# install besttrace
if [ ! -f "besttrace2021" ]; then
    arch=$(uname -m)
    if [ "${arch}" == "i686" ]; then
        wget -O besttrace2021 https://github.com/flyzy2005/shell/raw/master/besttrace32
    else
        wget https://github.com/flyzy2005/shell/raw/master/besttrace2021
    fi
    # unzip besttrace4linux.zip
    chmod +x besttrace2021
fi

## start to use besttrace

next() {
    printf "%-70s\n" "-" | sed 's/\s/-/g'
}

clear
next

ip_list=(223.166.96.199  101.82.207.128    101.95.104.70  42.120.74.90 221.229.173.0 113.246.68.203 111.183.61.7 14.215.116.1 117.28.254.129 113.207.25.138 119.6.6.6 120.204.197.126 183.221.253.100 202.112.14.151)
ip_addr=(上海联通商宽  上海电信4g   上海电信 杭州阿里云 江苏徐州电信 长沙电信 武汉电信4g 广州电信 厦门电信 重庆联通 成都联通 上海移动 成都移动 成都教育网)

#ip_len=${#ip_list[@]}

for i in {0..13}; do
    echo ${ip_addr[$i]}
    ./besttrace2021 -q 1 ${ip_list[$i]}
    next
done
